export const scenes = [
  {
    id: "kitchen",
    english: "Kitchen",
    chinese: "厨房",
    description: "从做饭、收纳到清洁，认识厨房里每天都会碰到的物品。",
    preview: "微波炉、橱柜、水龙头",
    image: "assets/images/scenes/kitchen.webp",
    query: "modern home kitchen interior",
  },
  {
    id: "living-room",
    english: "Living room",
    chinese: "客厅",
    description: "学习休息、看电视和招待客人时常用的客厅词汇。",
    preview: "沙发、茶几、窗帘",
    image: "assets/images/scenes/living-room.webp",
    query: "cozy living room interior",
  },
  {
    id: "bedroom",
    english: "Bedroom",
    chinese: "卧室",
    description: "从床上用品到衣物收纳，描述自己的卧室和睡眠习惯。",
    preview: "床头柜、衣柜、枕头",
    image: "assets/images/scenes/bedroom.webp",
    query: "cozy bedroom interior",
  },
  {
    id: "bathroom",
    english: "Bathroom",
    chinese: "浴室",
    description: "掌握洗漱、洗澡和清洁时最常见的浴室物品。",
    preview: "洗脸池、浴巾、淋浴",
    image: "assets/images/scenes/bathroom.webp",
    query: "modern bathroom interior",
  },
  {
    id: "office",
    english: "Office",
    chinese: "办公室",
    description: "认识办公桌周围的设备、文具和文件收纳用品。",
    preview: "订书机、文件柜、插座",
    image: "assets/images/scenes/office.webp",
    query: "modern office workspace",
  },
  {
    id: "neighborhood",
    english: "Neighborhood",
    chinese: "街区",
    description: "学习出门后会看到的道路设施、商店和公共物品。",
    preview: "人行道、红绿灯、长椅",
    image: "assets/images/scenes/neighborhood.webp",
    query: "urban neighborhood street",
  },
];

const vocabulary = {
  kitchen: [
    ["microwave", "微波炉", "/ˈmaɪkrəweɪv/", "heat it in the microwave", "I’ll heat the food in the microwave.", "microwave oven appliance"],
    ["cabinet", "橱柜；柜子", "/ˈkæbɪnət/", "open the cabinet", "The cups are in the cabinet.", "kitchen cabinet"],
    ["faucet", "水龙头", "/ˈfɔːsɪt/", "turn off the faucet", "Please turn off the faucet.", "kitchen faucet tap"],
    ["stool", "凳子", "/stuːl/", "sit on a stool", "He is sitting on a kitchen stool.", "kitchen stool"],
    ["refrigerator", "冰箱", "/rɪˈfrɪdʒəreɪtər/", "put it in the refrigerator", "The milk is in the refrigerator.", "refrigerator appliance"],
    ["freezer", "冷冻柜；冰柜", "/ˈfriːzər/", "keep it in the freezer", "I keep frozen food in the freezer.", "freezer appliance"],
    ["stove", "炉灶", "/stoʊv/", "cook on the stove", "The soup is cooking on the stove.", "kitchen stove"],
    ["oven", "烤箱", "/ˈʌvən/", "preheat the oven", "Preheat the oven to 180 degrees.", "kitchen oven"],
    ["sink", "水槽", "/sɪŋk/", "leave it in the sink", "The dirty plates are in the sink.", "kitchen sink"],
    ["dishwasher", "洗碗机", "/ˈdɪʃwɑːʃər/", "load the dishwasher", "Can you load the dishwasher?", "dishwasher appliance"],
    ["kettle", "水壶", "/ˈketl/", "boil the kettle", "I’ll boil the kettle for tea.", "electric kettle"],
    ["toaster", "烤面包机", "/ˈtoʊstər/", "put bread in the toaster", "The bread is in the toaster.", "bread toaster appliance"],
    ["blender", "搅拌机", "/ˈblendər/", "use the blender", "I use the blender to make smoothies.", "kitchen blender"],
    ["cutting-board", "砧板", "/ˈkʌtɪŋ bɔːrd/", "put it on the cutting board", "Cut the onion on the cutting board.", "wooden cutting board"],
    ["frying-pan", "煎锅", "/ˈfraɪɪŋ pæn/", "heat the frying pan", "Heat some oil in the frying pan.", "frying pan"],
    ["pot", "锅", "/pɑːt/", "cover the pot", "The rice is cooking in the pot.", "cooking pot"],
    ["spatula", "锅铲", "/ˈspætʃələ/", "flip it with a spatula", "Use a spatula to flip the egg.", "kitchen spatula"],
    ["knife", "刀", "/naɪf/", "cut it with a knife", "Be careful with that sharp knife.", "kitchen knife"],
    ["plate", "盘子", "/pleɪt/", "put it on a plate", "Put the fruit on a plate.", "ceramic dinner plate"],
    ["bowl", "碗", "/boʊl/", "a bowl of rice", "Would you like a bowl of rice?", "ceramic bowl"],
  ],
  "living-room": [
    ["sofa", "沙发", "/ˈsoʊfə/", "sit on the sofa", "Let’s sit on the sofa.", "living room sofa"],
    ["armchair", "扶手椅", "/ˈɑːrmtʃer/", "relax in the armchair", "Grandpa is reading in the armchair.", "armchair furniture"],
    ["coffee-table", "茶几", "/ˈkɔːfi teɪbl/", "on the coffee table", "Your keys are on the coffee table.", "living room coffee table"],
    ["television", "电视机", "/ˈtelɪvɪʒən/", "turn on the television", "Let’s turn on the television.", "television screen"],
    ["remote-control", "遥控器", "/rɪˈmoʊt kənˈtroʊl/", "find the remote control", "Where is the remote control?", "television remote control"],
    ["curtain", "窗帘", "/ˈkɜːrtn/", "close the curtains", "Please close the curtains.", "window curtains"],
    ["rug", "小地毯", "/rʌɡ/", "walk across the rug", "The rug feels soft under my feet.", "living room rug"],
    ["floor-lamp", "落地灯", "/ˈflɔːr læmp/", "switch on the floor lamp", "Switch on the floor lamp, please.", "floor lamp"],
    ["bookshelf", "书架", "/ˈbʊkʃelf/", "put it on the bookshelf", "The dictionary is on the bookshelf.", "bookshelf furniture"],
    ["cushion", "靠垫", "/ˈkʊʃən/", "lean on a cushion", "Put a cushion behind your back.", "sofa cushion"],
    ["blanket", "毯子", "/ˈblæŋkɪt/", "wrap up in a blanket", "I need a warm blanket.", "soft blanket"],
    ["window", "窗户", "/ˈwɪndoʊ/", "open the window", "Could you open the window?", "house window"],
    ["fireplace", "壁炉", "/ˈfaɪərpleɪs/", "sit by the fireplace", "We sat by the fireplace.", "home fireplace"],
    ["speaker", "音箱", "/ˈspiːkər/", "connect the speaker", "I connected my phone to the speaker.", "home audio speaker"],
    ["vase", "花瓶", "/veɪs/", "put flowers in a vase", "She put the flowers in a vase.", "flower vase"],
    ["wall-clock", "挂钟", "/ˈwɔːl klɑːk/", "look at the wall clock", "The wall clock says eight o’clock.", "wall clock"],
    ["picture-frame", "相框", "/ˈpɪktʃər freɪm/", "a photo in a frame", "That picture frame is from my mother.", "photo picture frame"],
    ["houseplant", "室内植物", "/ˈhaʊsplænt/", "water the houseplant", "Don’t forget to water the houseplant.", "potted houseplant"],
    ["ceiling-fan", "吊扇", "/ˈsiːlɪŋ fæn/", "turn on the ceiling fan", "The ceiling fan keeps the room cool.", "ceiling fan"],
    ["side-table", "边桌", "/ˈsaɪd teɪbl/", "beside the side table", "My glasses are on the side table.", "living room side table"],
  ],
  bedroom: [
    ["bed", "床", "/bed/", "make the bed", "I make the bed every morning.", "bed furniture"],
    ["pillow", "枕头", "/ˈpɪloʊ/", "rest on a pillow", "This pillow is too soft.", "bed pillow"],
    ["bedsheet", "床单", "/ˈbedʃiːt/", "change the bedsheet", "I change the bedsheet every week.", "bed sheet"],
    ["duvet", "羽绒被；被子", "/duːˈveɪ/", "pull up the duvet", "It’s cold, so pull up the duvet.", "bed duvet"],
    ["mattress", "床垫", "/ˈmætrəs/", "a firm mattress", "This mattress is very comfortable.", "bed mattress"],
    ["nightstand", "床头柜", "/ˈnaɪtstænd/", "on the nightstand", "My phone is on the nightstand.", "bedroom nightstand"],
    ["wardrobe", "衣柜", "/ˈwɔːrdroʊb/", "hang it in the wardrobe", "My coats are in the wardrobe.", "bedroom wardrobe"],
    ["dresser", "五斗柜", "/ˈdresər/", "in the dresser drawer", "The socks are in the dresser.", "bedroom dresser"],
    ["drawer", "抽屉", "/drɔːr/", "open the drawer", "Open the top drawer.", "wooden drawer"],
    ["hanger", "衣架", "/ˈhæŋər/", "put it on a hanger", "Put your shirt on a hanger.", "clothes hanger"],
    ["mirror", "镜子", "/ˈmɪrər/", "look in the mirror", "She looked at herself in the mirror.", "bedroom mirror"],
    ["alarm-clock", "闹钟", "/əˈlɑːrm klɑːk/", "set the alarm clock", "I set the alarm clock for seven.", "alarm clock"],
    ["bedside-lamp", "床头灯", "/ˈbedsaɪd læmp/", "turn off the bedside lamp", "Turn off the bedside lamp before sleep.", "bedside lamp"],
    ["laundry-basket", "洗衣篮", "/ˈlɔːndri bæskɪt/", "put it in the laundry basket", "Your clothes are in the laundry basket.", "laundry basket"],
    ["slippers", "拖鞋", "/ˈslɪpərz/", "put on your slippers", "I keep my slippers beside the bed.", "bedroom slippers"],
    ["closet", "壁橱；衣橱", "/ˈklɑːzɪt/", "clean out the closet", "Her shoes are in the closet.", "bedroom closet"],
    ["desk", "书桌", "/desk/", "sit at the desk", "I sometimes study at my desk.", "bedroom desk"],
    ["chair", "椅子", "/tʃer/", "pull up a chair", "There is a chair by the window.", "wooden chair"],
    ["air-conditioner", "空调", "/ˈer kəndɪʃənər/", "turn on the air conditioner", "The air conditioner is too cold.", "air conditioner indoor unit"],
    ["clothes-rack", "衣帽架", "/ˈkloʊðz ræk/", "hang it on the clothes rack", "My jacket is on the clothes rack.", "clothes rack"],
  ],
  bathroom: [
    ["sink", "洗脸池", "/sɪŋk/", "wash it in the sink", "I left my toothbrush by the sink.", "bathroom sink"],
    ["toilet", "马桶", "/ˈtɔɪlət/", "flush the toilet", "Please remember to flush the toilet.", "bathroom toilet"],
    ["shower", "淋浴", "/ˈʃaʊər/", "take a shower", "I usually take a shower at night.", "bathroom shower"],
    ["bathtub", "浴缸", "/ˈbæθtʌb/", "fill the bathtub", "The children are playing in the bathtub.", "bathroom bathtub"],
    ["towel", "毛巾", "/ˈtaʊəl/", "dry your hands with a towel", "Here is a clean towel.", "bath towel"],
    ["bath-mat", "浴室防滑垫", "/ˈbæθ mæt/", "step onto the bath mat", "The bath mat is wet.", "bath mat"],
    ["toothbrush", "牙刷", "/ˈtuːθbrʌʃ/", "use a toothbrush", "I need a new toothbrush.", "toothbrush"],
    ["toothpaste", "牙膏", "/ˈtuːθpeɪst/", "a tube of toothpaste", "We’re almost out of toothpaste.", "toothpaste tube"],
    ["soap", "肥皂", "/soʊp/", "wash with soap", "Wash your hands with soap.", "bar of soap"],
    ["shampoo", "洗发水", "/ʃæmˈpuː/", "a bottle of shampoo", "This shampoo smells nice.", "shampoo bottle"],
    ["conditioner", "护发素", "/kənˈdɪʃənər/", "use hair conditioner", "Use conditioner after shampoo.", "hair conditioner bottle"],
    ["razor", "剃须刀", "/ˈreɪzər/", "shave with a razor", "Be careful with the razor.", "shaving razor"],
    ["hairdryer", "吹风机", "/ˈherdraɪər/", "use the hairdryer", "I use the hairdryer every morning.", "hair dryer"],
    ["toilet-paper", "卫生纸", "/ˈtɔɪlət peɪpər/", "a roll of toilet paper", "We need more toilet paper.", "toilet paper roll"],
    ["medicine-cabinet", "药柜", "/ˈmedɪsɪn kæbɪnət/", "check the medicine cabinet", "The bandages are in the medicine cabinet.", "bathroom medicine cabinet"],
    ["scale", "体重秤", "/skeɪl/", "step on the scale", "I stepped on the scale this morning.", "bathroom weighing scale"],
    ["comb", "梳子", "/koʊm/", "comb your hair", "This is my wooden comb.", "hair comb"],
    ["tissue-box", "纸巾盒", "/ˈtɪʃuː bɑːks/", "take a tissue", "There is a tissue box by the sink.", "tissue box"],
    ["shower-curtain", "浴帘", "/ˈʃaʊər kɜːrtn/", "close the shower curtain", "Close the shower curtain first.", "shower curtain"],
    ["bathrobe", "浴袍", "/ˈbæθroʊb/", "put on a bathrobe", "She put on a warm bathrobe.", "bathrobe"],
  ],
  office: [
    ["desk", "办公桌", "/desk/", "at my desk", "I left the document on my desk.", "office desk"],
    ["office-chair", "办公椅", "/ˈɔːfɪs tʃer/", "adjust the office chair", "This office chair supports my back.", "office chair"],
    ["computer", "电脑", "/kəmˈpjuːtər/", "turn on the computer", "My computer is running slowly.", "desktop computer"],
    ["monitor", "显示器", "/ˈmɑːnɪtər/", "look at the monitor", "The monitor is too bright.", "computer monitor"],
    ["keyboard", "键盘", "/ˈkiːbɔːrd/", "type on the keyboard", "There is dust on the keyboard.", "computer keyboard"],
    ["mouse", "鼠标", "/maʊs/", "click the mouse", "My wireless mouse needs a battery.", "computer mouse"],
    ["printer", "打印机", "/ˈprɪntər/", "use the printer", "The printer is out of paper.", "office printer"],
    ["photocopier", "复印机", "/ˈfoʊtoʊkɑːpiər/", "use the photocopier", "The photocopier is near the door.", "office photocopier"],
    ["stapler", "订书机", "/ˈsteɪplər/", "staple the pages", "Can I borrow your stapler?", "office stapler"],
    ["paper-clip", "回形针", "/ˈpeɪpər klɪp/", "hold it with a paper clip", "Use a paper clip for these pages.", "paper clip"],
    ["notebook", "笔记本", "/ˈnoʊtbʊk/", "write in a notebook", "I wrote the number in my notebook.", "paper notebook"],
    ["pen", "笔", "/pen/", "write with a pen", "Do you have a blue pen?", "ballpoint pen"],
    ["pencil", "铅笔", "/ˈpensl/", "use a pencil", "Draw the line with a pencil.", "wooden pencil"],
    ["highlighter", "荧光笔", "/ˈhaɪlaɪtər/", "mark it with a highlighter", "I marked the key sentence with a highlighter.", "highlighter pen"],
    ["file-cabinet", "文件柜", "/ˈfaɪl kæbɪnət/", "check the file cabinet", "The old contracts are in the file cabinet.", "office file cabinet"],
    ["folder", "文件夹", "/ˈfoʊldər/", "put it in a folder", "Keep these papers in the blue folder.", "document folder"],
    ["power-outlet", "电源插座", "/ˈpaʊər aʊtlet/", "plug it into the outlet", "Is there a power outlet near here?", "electrical power outlet"],
    ["charger", "充电器", "/ˈtʃɑːrdʒər/", "connect the charger", "I forgot my laptop charger.", "laptop charger"],
    ["whiteboard", "白板", "/ˈwaɪtbɔːrd/", "write on the whiteboard", "The plan is on the whiteboard.", "office whiteboard"],
    ["trash-can", "垃圾桶", "/ˈtræʃ kæn/", "throw it in the trash can", "The trash can is under the desk.", "office trash can"],
  ],
  neighborhood: [
    ["sidewalk", "人行道", "/ˈsaɪdwɔːk/", "walk on the sidewalk", "Please stay on the sidewalk.", "city sidewalk"],
    ["crosswalk", "人行横道", "/ˈkrɔːswɔːk/", "use the crosswalk", "Let’s cross at the crosswalk.", "pedestrian crosswalk"],
    ["traffic-light", "红绿灯", "/ˈtræfɪk laɪt/", "wait at the traffic light", "Turn left at the traffic light.", "traffic light"],
    ["street-sign", "路牌", "/ˈstriːt saɪn/", "read the street sign", "I can’t see the street sign.", "street sign"],
    ["bench", "长椅", "/bentʃ/", "sit on a bench", "Let’s rest on that bench.", "park bench"],
    ["bus-stop", "公交车站", "/ˈbʌs stɑːp/", "wait at the bus stop", "The bus stop is across the street.", "bus stop"],
    ["mailbox", "邮箱", "/ˈmeɪlbɑːks/", "put it in the mailbox", "There is a mailbox on the corner.", "street mailbox"],
    ["trash-bin", "垃圾箱", "/ˈtræʃ bɪn/", "use the trash bin", "Please put the bottle in the trash bin.", "public trash bin"],
    ["streetlamp", "路灯", "/ˈstriːtlæmp/", "under the streetlamp", "The streetlamp turns on at night.", "street lamp"],
    ["fire-hydrant", "消防栓", "/ˈfaɪər haɪdrənt/", "next to the fire hydrant", "Don’t park beside the fire hydrant.", "fire hydrant"],
    ["parking-meter", "停车计时器", "/ˈpɑːrkɪŋ miːtər/", "pay at the parking meter", "The parking meter takes coins.", "parking meter"],
    ["bicycle-rack", "自行车架", "/ˈbaɪsɪkl ræk/", "lock it to the bicycle rack", "My bike is at the bicycle rack.", "bicycle rack"],
    ["storefront", "店面", "/ˈstɔːrfrʌnt/", "look at the storefront", "The storefront has a red sign.", "shop storefront"],
    ["bakery", "面包店", "/ˈbeɪkəri/", "go to the bakery", "I bought fresh bread at the bakery.", "neighborhood bakery"],
    ["pharmacy", "药店", "/ˈfɑːrməsi/", "stop at the pharmacy", "The pharmacy closes at nine.", "pharmacy storefront"],
    ["supermarket", "超市", "/ˈsuːpərmɑːrkɪt/", "go to the supermarket", "We need to stop at the supermarket.", "supermarket exterior"],
    ["apartment-building", "公寓楼", "/əˈpɑːrtmənt bɪldɪŋ/", "live in an apartment building", "She lives in that apartment building.", "apartment building"],
    ["fence", "栅栏", "/fens/", "behind the fence", "The garden is behind the fence.", "street fence"],
    ["gate", "大门；栅栏门", "/ɡeɪt/", "open the gate", "Please close the gate behind you.", "garden gate"],
    ["manhole-cover", "井盖", "/ˈmænhoʊl kʌvər/", "avoid the manhole cover", "The manhole cover is slippery.", "manhole cover street"],
  ],
};

export const words = Object.entries(vocabulary).flatMap(([scene, entries]) =>
  entries.map(([slug, chinese, phonetic, phrase, example, query]) => ({
    id: `${scene}-${slug}`,
    scene,
    english: slug.replaceAll("-", " "),
    chinese,
    phonetic,
    phrase,
    example,
    query,
    image: `assets/images/words/${scene}/${slug}.webp`,
  })),
);
